### ISSUE TITLE
大佬你好，添加用例描述要怎么操作呢？

### ISSUE THREAD

**Issue by git564733702** [mocobk/BeautifulReport#1]
添加用例描述要怎么操作呢？我看到示例有用例描述的
![用例描述](https://user-images.githubusercontent.com/48816144/60638929-eea7ec00-9e52-11e9-8f61-93353f87c6bc.png)
，但我的都是显示null

**Comment by mocobk** [comment]
用例描述来自于用例方法中的 __doc__ ，如
```python
def test_demo(self):
    "这里是用例描述"
    ...
