### ISSUE TITLE
为什么Template（图片路径）会影响报告生成的图片img标签

### ISSUE THREAD

**Issue by a3247858** [mocobk/BeautifulReport#2]
比如if exists(Template(r"..\oppoimg\shiming.png", record_pos=(-0.033, -0.0), resolution=(2340, 1080)))
Template里的图片路径，会让报告里的图片不显示，经查看报告源码，发现里面的img标签变成了oppoimg标签，因此不显示，想知道为啥，求大佬指点

**Comment by mocobk** [comment]
img 存放位置使用了硬编码, 只会从当前目录的img文件夹中查找，至于你说的标签变了，需要再看看
```python
img_path = 'img/' if platform.system() != 'Windows' else 'img\\'
```
